export const dataJalan = [
{
    "FID": 0,
    "ID": 28,
    "NAMA_RUAS": "WEHALI - BATAS MAYBRAT",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 3.523,
    "LEBAR_M": 6,
    "LAPEN_KM": 3.523,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 3.523,
    "BAIK__PERS": "100%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "PROVINSI",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\28. Wehali - Batas Maybrat\\25' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img arc= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\28. Wehali - Batas Maybrat\\7.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "3+523"
},
{
    "FID": 1,
    "ID": 2,
    "NAMA_RUAS": "WENSLOLO - SESNEK",
    "KECAMATAN_": "SAWIAT",
    "PANJANG_KM": 8.679,
    "LEBAR_M": 5,
    "LAPEN_KM": 2.156,
    "BETON_KM": 0.117,
    "TELFORD_KE": 6.4,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 2.339,
    "BAIK__PERS": "26,96%",
    "SEDANG_KM": 5,
    "SEDANG_PER": "57,61%",
    "RUSAKRINGA": 1.34,
    "RUSAKRIN00": "15,44%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 02\\52.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 02\\41.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 02\\46.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 03\\76.jpg' width='300'/>",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 02\\38.jpg' width='300'/>",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\02. Wenslolo - Sasnek Part 02\\36.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 0+353, 0+403, 0+851, 4+004, 4+4223, 4+325, 4+500, 4+560, 4+583, 4+901, 5+153, 5+270, 5+400, 5+628, 6+129, 6+158,  6+342, 6+374, 6+722, 6+938, 7+942, 8+292,  8+325",
    "STA_AKHIR": "0+353, 0+403, 0+851, 4+004, 4+223, 4+325,4+500, 4+560,4+583, 4+901,4+951, 5+153,5+270, 5+400,5+628, 6+129, 6+158, 6+342, 6+374, 6+722, 6+938, 7+942, 8+292, 8+325, 8+679"
},
{
    "FID": 2,
    "ID": 8,
    "NAMA_RUAS": "MANGGROHOLO - KWOWOK",
    "KECAMATAN_": "SAIFI",
    "PANJANG_KM": 2.297,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 2.297,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0.00%",
    "SEDANG_KM": 0.897,
    "SEDANG_PER": "39,05",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "05",
    "RUSAKBERAT": 1.4,
    "RUSAKBER00": "60,95%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\08. Manggroholo - Kwowok\\22.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\08. Manggroholo - Kwowok\\11.jpg' width='300'>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\08. Manggroholo - Kwowok\\18.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "2+297"
},
{
    "FID": 3,
    "ID": 1,
    "NAMA_RUAS": "MLABOLO - KOFALIT",
    "KECAMATAN_": "SAWIAT",
    "PANJANG_KM": 4.742,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0.675,
    "BETON_KM": 0,
    "TELFORD_KE": 4.067,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.675,
    "BAIK__PERS": "14,23%",
    "SEDANG_KM": 1.664,
    "SEDANG_PER": "35,09%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 2.403,
    "RUSAKBER00": "50,67%",
    "LHR": 0,
    "AKSES_KE_N": "N",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_141722.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_134115.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_134227.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_131952.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_135833.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\01. Mlabolo - Kofalit\\20181024_140353.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 1+664, 2+023, 3+160, 3+336, 3+375, 3+515",
    "STA_AKHIR": "1+664, 2+023, 3+160, 3+336, 3+375, 3+515, 4+742"
},
{
    "FID": 4,
    "ID": 29,
    "NAMA_RUAS": "WAIGO - UNGGI",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 5.036,
    "LEBAR_M": 0,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 5.036,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0.00%",
    "SEDANG_KM": 2.235,
    "SEDANG_PER": "44,4%",
    "RUSAKRINGA": 2.8,
    "RUSAKRIN00": "55,6",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\29. Waigo - Unggi\\2.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\29. Waigo - Unggi\\36.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\29. Waigo - Unggi\\12.pg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "5+036"
},
{
    "FID": 5,
    "ID": 33,
    "NAMA_RUAS": "MOSWAREN - KAMISABE",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 5.828,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0.789,
    "BETON_KM": 0,
    "TELFORD_KE": 5.03,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.798,
    "BAIK__PERS": "13,69%",
    "SEDANG_KM": 1.202,
    "SEDANG_PER": "20,62%",
    "RUSAKRINGA": 3.828,
    "RUSAKRIN00": "65,68",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\33. Moswaren - Kamisabe\\2.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\33. Moswaren - Kamisabe\\8.jpg' width='300'/.",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\33. Moswaren - Kamisabe\\5.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\33. Moswaren - Kamisabe\\3.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\33. Moswaren - Kamisabe\\5.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 0+798",
    "STA_AKHIR": "0+798, 5+828"
},
{
    "FID": 6,
    "ID": 22,
    "NAMA_RUAS": "TVRI - AIBOBOR",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 3.131,
    "LEBAR_M": 5,
    "LAPEN_KM": 3131,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 3131,
    "BAIK__PERS": "100,00%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\22. TVRI - Aibobor\\8.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\22. TVRI - Aibobor\\5.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "3+131"
},
{
    "FID": 7,
    "ID": 0,
    "NAMA_RUAS": "TEMINABUAN - KLAMIT",
    "KECAMATAN_": "SAWIAT-SEREMUK-TEMINABUAN",
    "PANJANG_KM": 39.72,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 39,
    "BETON_KM": 0.72,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 24.229,
    "BAIK__PERS": "61.00%",
    "SEDANG_KM": 10.724,
    "SEDANG_PER": "27.000%",
    "RUSAKRINGA": 4.766,
    "RUSAKRIN00": "12.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 100,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 8,
    "ID": 6,
    "NAMA_RUAS": "SRER - SISIR",
    "KECAMATAN_": "SEREMUK-SAIFI",
    "PANJANG_KM": 19.84,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 5.932,
    "BETON_KM": 0,
    "TELFORD_KE": 13.908,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 3.636,
    "BAIK__PERS": "18,33%",
    "SEDANG_KM": 8.231,
    "SEDANG_PER": "41,49%",
    "RUSAKRINGA": 7.973,
    "RUSAKRIN00": "40,19%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\06. Srer - Sisir\\5.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\06. Srer - Sisir\\29.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\06. Srer - Sisir\\40.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\06. Srer - Sisir\\6.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\06. Srer - Sisir\\160.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 5+004, 5+365, 6+293,",
    "STA_AKHIR": "5+004, 5+365, 6+293, 19+840"
},
{
    "FID": 9,
    "ID": 26,
    "NAMA_RUAS": "BOLDON - SESOR",
    "KECAMATAN_": "WAYER-TEMINABUAN",
    "PANJANG_KM": 4.542,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 4.542,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 45.42,
    "SEDANG_PER": "100%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\26. Boldon - Sesor\\30.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\26. Boldon - Sesor\\10.jpg' width",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "4+542"
},
{
    "FID": 10,
    "ID": 31,
    "NAMA_RUAS": "MOSWAREN - SP1 - JOKSIRO",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 15.3,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 7.902,
    "BETON_KM": 0,
    "TELFORD_KE": 7.398,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 7.903,
    "BAIK__PERS": "51,65%",
    "SEDANG_KM": 7.397,
    "SEDANG_PER": "48,35%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\31. Moswaren - SP1 - Joksiro\\8.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\31. Moswaren - SP1 - Joksiro\\18.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\31. Moswaren - SP1 - Joksiro\\4.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\31. Moswaren - SP1 - Joksiro\\43.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 6+729, 13+484, 14+658",
    "STA_AKHIR": "6+729, 13+484, 14+658, 15+300"
},
{
    "FID": 11,
    "ID": 0,
    "NAMA_RUAS": "SESNA - PERTIGAAN AITINYO",
    "KECAMATAN_": "WAYER-MOSWAREN",
    "PANJANG_KM": 28.32,
    "LEBAR_M": 6,
    "LAPEN_KM": 28.32,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 19.824,
    "BAIK__PERS": "70.00%",
    "SEDANG_KM": 6.23,
    "SEDANG_PER": "22.000%",
    "RUSAKRINGA": 2.266,
    "RUSAKRIN00": "8.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "PROVINSI",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 12,
    "ID": 18,
    "NAMA_RUAS": "FAN OTTO IHALAUW",
    "KECAMATAN_": "TEMINABUAN-KONDA",
    "PANJANG_KM": 24,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 11.46,
    "BETON_KM": 2.429,
    "TELFORD_KE": 10.111,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 9.489,
    "BAIK__PERS": "39,54",
    "SEDANG_KM": 1.245,
    "SEDANG_PER": "5,19",
    "RUSAKRINGA": 1.2,
    "RUSAKRIN00": 5,
    "RUSAKBERAT": 12.066,
    "RUSAKBER00": "50,28",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 11+200, 13+045, 13+318, 15+249,15+529,15+882,17+262, 17+521, 17+718, 18+603, 18+902",
    "STA_AKHIR": "11+200, 13+045, 13+318, 15+249,15+529,15+882,17+262, 17+521, 17+718, 18+603, 18+902, 24+000"
},
{
    "FID": 13,
    "ID": 11,
    "NAMA_RUAS": "SRER - GAMARO",
    "KECAMATAN_": "SEREMUK",
    "PANJANG_KM": 2.503,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0.554,
    "TELFORD_KE": 1.432,
    "TANAH_KM": 0.517,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.554,
    "BAIK__PERS": "22,13%",
    "SEDANG_KM": 1.432,
    "SEDANG_PER": "57,21%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0.517,
    "RUSAKBER00": "20,66",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\10.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\25.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\4.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\12.jpg' width='300'/>",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\29.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\11. Srer - Gamaro\\2.jpg' width='300'/>",
    "STA_AWAL": "0+000, 0+517, 1+071",
    "STA_AKHIR": "0+517, 1+071, 2+503"
},
{
    "FID": 14,
    "ID": 44,
    "NAMA_RUAS": "AKSES-TPA SENGGUER",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 2.3,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0.895,
    "BETON_KM": 0,
    "TELFORD_KE": 1.405,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.895,
    "BAIK__PERS": "38,91%",
    "SEDANG_KM": 1.405,
    "SEDANG_PER": "61,09%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\44. Akses - TPA Sungguer\\1+400.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\44. Akses - TPA Sungguer\\0+700.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\44. Akses - TPA Sungguer\\0+250.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\44. Akses - TPA Sungguer\\1+150.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 1+277, 2+065, 2+193",
    "STA_AKHIR": "1+277, 2+065, 2+193, 2+300"
},
{
    "FID": 15,
    "ID": 0,
    "NAMA_RUAS": "KLAMIT - PASIR PUTIH",
    "KECAMATAN_": "SAWIAT-FKOUR",
    "PANJANG_KM": 22.3,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 22.3,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 18.286,
    "BAIK__PERS": "82.00%",
    "SEDANG_KM": 3.568,
    "SEDANG_PER": "16.000%",
    "RUSAKRINGA": 0.446,
    "RUSAKRIN00": "2.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 50,
    "AKSES_KE_N": "N",
    "KETERANGAN": "NASIONAL",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 16,
    "ID": 37,
    "NAMA_RUAS": "KAMRO - MUKAMAT",
    "KECAMATAN_": "KAIS",
    "PANJANG_KM": 16.04,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 16.04,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0.2,
    "SEDANG_PER": "1,25%",
    "RUSAKRINGA": 15.84,
    "RUSAKRIN00": 98.75,
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\37. Kamro - Mukamat - Part 01\\3.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\37. Kamro - Mukamat - Part 01\\16.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\37. Kamro - Mukamat - Part 01\\5.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "16+040"
},
{
    "FID": 17,
    "ID": 32,
    "NAMA_RUAS": "MOSWAREN - SP2 - WARDIK",
    "KECAMATAN_": "MOSWAREN-WAYER",
    "PANJANG_KM": 13.74,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 3.294,
    "BETON_KM": 0.713,
    "TELFORD_KE": 8.609,
    "TANAH_KM": 1.124,
    "BELUMTEMBU": 0,
    "BAIK_KM": 4.006,
    "BAIK__PERS": "29,16%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 8.61,
    "RUSAKRIN00": "62,66%",
    "RUSAKBERAT": 1.124,
    "RUSAKBER00": "8,18%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\19.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\43.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\57' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\14.jpg' width='300'/>",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\46.jpg' width='300'/>",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\60.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\32. Moswaren - SP2 - Wardik\\65.jpg' width='300'/>",
    "STA_AWAL": "0+000, 1+901, 2+445, 3+837, 12+000, 12+616",
    "STA_AKHIR": "1+901, 2+445, 3+837, 12+000, 12+616, 13+740"
},
{
    "FID": 18,
    "ID": 49,
    "NAMA_RUAS": "KALIAT - SESNA",
    "KECAMATAN_": "TEMINABUAN-WAYER",
    "PANJANG_KM": 8.503,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 8.503,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 7.503,
    "BAIK__PERS": "88,24%",
    "SEDANG_KM": 1,
    "SEDANG_PER": "11,76%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "8+503"
},
{
    "FID": 19,
    "ID": 9,
    "NAMA_RUAS": "MANGGROHOLO - KAYABO",
    "KECAMATAN_": "SAIFI",
    "PANJANG_KM": 6.496,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 6.496,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 2.095,
    "SEDANG_PER": "32,25%",
    "RUSAKRINGA": 4.401,
    "RUSAKRIN00": "67,75",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\09. Manggroholo - Kayabo - Terbaru\\4.j[g' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\09. Manggroholo - Kayabo - Terbaru\\12.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\09. Manggroholo - Kayabo - Terbaru\\2.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "6+496"
},
{
    "FID": 20,
    "ID": 23,
    "NAMA_RUAS": "WERNAS",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 0.681,
    "LEBAR_M": 4,
    "LAPEN_KM": 0.681,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.681,
    "BAIK__PERS": "100%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\23. Wernas\\6.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\23. Wernas\\9.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "0+681"
},
{
    "FID": 21,
    "ID": 16,
    "NAMA_RUAS": "WERSAR - TRIKORA",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 0.674,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0.674,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.674,
    "BAIK__PERS": "100%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0.000%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0,000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\16. Wersar - Trikora\\8.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\16. Wersar - Trikora\\6.jpg' width='300'/>",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "0+674"
},
{
    "FID": 22,
    "ID": 20,
    "NAMA_RUAS": "KONDA - DEMEN",
    "KECAMATAN_": "KONDA",
    "PANJANG_KM": 6.542,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0.996,
    "TANAH_KM": 5.586,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0.000%",
    "RUSAKRINGA": 0.956,
    "RUSAKRIN00": "14,61%",
    "RUSAKBERAT": 5.586,
    "RUSAKBER00": "85,39%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\20. Konda - Demen\\2.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\20. Konda - Demen\\14.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\20. Konda - Demen\\4.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\20. Konda - Demen\\34.jpg' width='300'/>",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 23,
    "ID": 3,
    "NAMA_RUAS": "SODORFOYO - ELES",
    "KECAMATAN_": "SAWIAT",
    "PANJANG_KM": 5.804,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 5.016,
    "BETON_KM": 0,
    "TELFORD_KE": 0.788,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 5.016,
    "BAIK__PERS": "86,42%",
    "SEDANG_KM": 0.788,
    "SEDANG_PER": "13,58%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\03. Sodrofoyo - Elles\\30.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\03. Sodrofoyo - Elles\\11.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\03. Sodrofoyo - Elles\\2.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\03. Sodrofoyo - Elles\\35.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 0+740, 1+350, 1+689, 1+867",
    "STA_AKHIR": "0+740, 1+350, 1+689, 1+867, 5+804"
},
{
    "FID": 24,
    "ID": 19,
    "NAMA_RUAS": "BARIAT - NAKNA",
    "KECAMATAN_": "KONDA",
    "PANJANG_KM": 11.28,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0.44,
    "BETON_KM": 1.913,
    "TELFORD_KE": 8.946,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 2.344,
    "BAIK__PERS": "20,69",
    "SEDANG_KM": 2.99,
    "SEDANG_PER": "26,51%",
    "RUSAKRINGA": 0.956,
    "RUSAKRIN00": "8,48%",
    "RUSAKBERAT": 5,
    "RUSAKBER00": "44,33%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\2.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\11.jpg' width='300'/.",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\1.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\4.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\6.jpg' width='300'/>",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\9.jpg' width='300'/>",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\19. Bariat - Nakna\\148.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 0+303, 0+432, 0+970, 1+182, 1+377, 1+610, 2+487, 10+244, 10+665",
    "STA_AKHIR": "0+303, 0+432, 0+970, 1+182, 1+377, 1+610, 2+487, 10+244, 10+665, 11+280"
},
{
    "FID": 25,
    "ID": 0,
    "NAMA_RUAS": "RUAS BATU PAYUNG - KLAMIT",
    "KECAMATAN_": "SAWIAT",
    "PANJANG_KM": 12.84,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 12.84,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 8.988,
    "BAIK__PERS": "70.00%",
    "SEDANG_KM": 2.183,
    "SEDANG_PER": "17.000%",
    "RUSAKRINGA": 1.669,
    "RUSAKRIN00": "13.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0.000%",
    "LHR": 150,
    "AKSES_KE_N": "N",
    "KETERANGAN": "NASIONAL",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 26,
    "ID": 4,
    "NAMA_RUAS": "TOFOT - HAHA - WOLOIN",
    "KECAMATAN_": "SEREMUK",
    "PANJANG_KM": 10.2,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 7.075,
    "BETON_KM": 0,
    "TELFORD_KE": 3.125,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 7.075,
    "BAIK__PERS": "69,36%",
    "SEDANG_KM": 3.125,
    "SEDANG_PER": "30,64%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\04. Tofot - Haha - Woloin\\IMG_20191113_092755.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\04. Tofot - Haha - Woloin\\IMG_20191113_093025.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\04. Tofot - Haha - Woloin\\IMG_20191113_092953.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\04. Tofot - Haha - Woloin\\IMG_20191113_094800.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 7+075",
    "STA_AKHIR": "7+075, 10+200"
},
{
    "FID": 27,
    "ID": 5,
    "NAMA_RUAS": "WOLOIN - KAKAS",
    "KECAMATAN_": "SEREMUK",
    "PANJANG_KM": 4.895,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 4.895,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 4.895,
    "SEDANG_PER": "100,00%",
    "RUSAKRINGA": 1.469,
    "RUSAKRIN00": "30.000%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\05. Woloin - Kakas\\11.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\05. Woloin - Kakas\\11.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "4+895"
},
{
    "FID": 28,
    "ID": 27,
    "NAMA_RUAS": "SESOR - HAJIR",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 3.059,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 3.059,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 3.05,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\27. Sesor - Hajir\\3.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\27. Sesor - Hajir\\5.pg' width='300'/>",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "3+059"
},
{
    "FID": 29,
    "ID": 30,
    "NAMA_RUAS": "WAIGO - SEFOTAMIN",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 1.54,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 1.54,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0.00%",
    "SEDANG_KM": 1.54,
    "SEDANG_PER": "100%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\30. Waigo - Sefotamin\\9.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\30. Waigo - Sefotamin\\13.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "1+540"
},
{
    "FID": 30,
    "ID": 50,
    "NAMA_RUAS": "JALAN TOKAS",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 2.692,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0.396,
    "BETON_KM": 0,
    "TELFORD_KE": 1.727,
    "TANAH_KM": 0.569,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.396,
    "BAIK__PERS": "14,71%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 1.727,
    "RUSAKRIN00": "64,15%",
    "RUSAKBERAT": 0.569,
    "RUSAKBER00": "21,14%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\6.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\2.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\23.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\16.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\17.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\50. Jalan Tokas\\19.jpg' width='300'/>",
    "STA_AWAL": "0+000, 0+569, 0+639, 1+035",
    "STA_AKHIR": "0+569, 0+639, 1+035, 2+692"
},
{
    "FID": 31,
    "ID": 12,
    "NAMA_RUAS": "SERIBAU - DERMAGA",
    "KECAMATAN_": "SEREMUK",
    "PANJANG_KM": 0.46,
    "LEBAR_M": 5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0.46,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0.46,
    "SEDANG_PER": "100%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\12. Seribau - Dermaga\\7.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\12. Seribau - Dermaga\\3.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "0+460"
},
{
    "FID": 32,
    "ID": 24,
    "NAMA_RUAS": "UNGGI - HAJIR",
    "KECAMATAN_": "WAYER-MOSWAREN",
    "PANJANG_KM": 5.567,
    "LEBAR_M": 6,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 5.567,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": 0,
    "RUSAKBERAT": 5.567,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\24. Unggi - Hajir\\40.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\24. Unggi - Hajir\\6.jpg' width='300'/>",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "5+567"
},
{
    "FID": 33,
    "ID": 17,
    "NAMA_RUAS": "KOMPLEKS KANTOR BUPATI",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 8.937,
    "LEBAR_M": 6,
    "LAPEN_KM": 8.937,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 8.937,
    "BAIK__PERS": "100,000%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0,00%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0,00",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\17. Kompleks Kantor Bupati\\15.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": 5,
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\17. Kompleks Kantor Bupati\\2.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "8+937"
},
{
    "FID": 34,
    "ID": 21,
    "NAMA_RUAS": "LINGKAR RUMAHSAKIT - KOWA",
    "KECAMATAN_": "WAYER",
    "PANJANG_KM": 4.295,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 4.295,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "05",
    "RUSAKRINGA": 2.295,
    "RUSAKRIN00": "53,43%",
    "RUSAKBERAT": 2,
    "RUSAKBER00": "46,57%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\21. Lingkar Rumah Sakit - Kowa\\15.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\21. Lingkar Rumah Sakit - Kowa\\21.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\21. Lingkar Rumah Sakit - Kowa\\2.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "4+295"
},
{
    "FID": 35,
    "ID": 13,
    "NAMA_RUAS": "DALAM KOTA TEMINABUAN",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 23.58,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 23.58,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 15.58,
    "BAIK__PERS": "66,07%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0.000%",
    "RUSAKRINGA": 8,
    "RUSAKRIN00": "33,93%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 450,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\13. Dalam Kota Teminabuan\\105.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\13. Dalam Kota Teminabuan\\15.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\13. Dalam Kota Teminabuan\\11.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "23+580"
},
{
    "FID": 36,
    "ID": 41,
    "NAMA_RUAS": "BENAWA I - BENAWA II",
    "KECAMATAN_": "KOKODA UTARA-KOKODA",
    "PANJANG_KM": 24.49,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 24.49,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 24.49,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "24+490"
},
{
    "FID": 37,
    "ID": 38,
    "NAMA_RUAS": "INANWATAN - BEDARE - PURAGI - SUMANO",
    "KECAMATAN_": "INAWATAN-METAMANI-KAIS",
    "PANJANG_KM": 72.67,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 72.67,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 72670,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\38. Inanwatan - Bedare - Puragi - Sumano\\12.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\38. Inanwatan - Bedare - Puragi - Sumano\\1.jpg width='300'/>",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "72,670"
},
{
    "FID": 38,
    "ID": 47,
    "NAMA_RUAS": "BEDARE - ODIARE",
    "KECAMATAN_": "INAWATAN",
    "PANJANG_KM": 6.169,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 6.169,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 6.169,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "6+169"
},
{
    "FID": 39,
    "ID": 43,
    "NAMA_RUAS": "SERANGGO - MAKARORO",
    "KECAMATAN_": "KAIS",
    "PANJANG_KM": 8.539,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 8.539,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "05",
    "RUSAKBERAT": 8.539,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "8+539"
},
{
    "FID": 40,
    "ID": 46,
    "NAMA_RUAS": "PERTIGAAN SERANGGO - MOGOTEMIN",
    "KECAMATAN_": "KAIS",
    "PANJANG_KM": 3.22,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 3.22,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 3.22,
    "RUSAKRIN00": "100%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\46. Pertigaan Siranggo - Mogetemin - Part 01/6.jpg' width='300'/.",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\46. Pertigaan Siranggo - Mogetemin - Part 01\\12.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "3+220"
},
{
    "FID": 41,
    "ID": 35,
    "NAMA_RUAS": "JOKSIRO - HAIMARAN",
    "KECAMATAN_": "MOSWAREN-KAIS",
    "PANJANG_KM": 15.35,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 15.35,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 15.35,
    "SEDANG_PER": "100%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\35. Joksiro - Haimaran\\25.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\35. Joksiro - Haimaran\\32.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "15+350"
},
{
    "FID": 42,
    "ID": 36,
    "NAMA_RUAS": "HAIMARAN - SERANGGO - KAIS",
    "KECAMATAN_": "KAIS",
    "PANJANG_KM": 51.43,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 39.884,
    "TANAH_KM": 11.546,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 6,
    "SEDANG_PER": "11,67%",
    "RUSAKRINGA": 33.884,
    "RUSAKRIN00": "65,88%",
    "RUSAKBERAT": 11.546,
    "RUSAKBER00": "22,45%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\36. Haimaran - Siranggo - Kais\\2.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\36. Haimaran - Siranggo - Kais\\2.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 39+884",
    "STA_AKHIR": "39+884, 51+430"
},
{
    "FID": 43,
    "ID": 42,
    "NAMA_RUAS": "BENAWA II - UDAGAGA-NEBES-TAROF",
    "KECAMATAN_": "KOKODA",
    "PANJANG_KM": 41.95,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 41.95,
    "BELUMTEMBU": 41.95,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 41.95,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "41+950"
},
{
    "FID": 44,
    "ID": 40,
    "NAMA_RUAS": "TAROF - TAPAS",
    "KECAMATAN_": "KOKODA",
    "PANJANG_KM": 16.96,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 16.96,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 1.52,
    "BAIK__PERS": "7,37%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 15.71,
    "RUSAKRIN00": "92,63%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\40. Tarof - Tapas\\4.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\40. Tarof - Tapas\\7.jpg' width='300'/>",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\40. Tarof - Tapas\\1.jpg' width='300'/>",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "16+960"
},
{
    "FID": 45,
    "ID": 39,
    "NAMA_RUAS": "SUMANO - ATHORI",
    "KECAMATAN_": "KAIS-KOKODA UTARA",
    "PANJANG_KM": 42.7,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 42.7,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 42.7,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "42+700"
},
{
    "FID": 46,
    "ID": 15,
    "NAMA_RUAS": "WERSAR - PELABUHAN PERIKANAN",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 1.343,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 1.343,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.543,
    "BAIK__PERS": "40,43%",
    "SEDANG_KM": 0.8,
    "SEDANG_PER": "59,57%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\15. Wersar - Pelabuhan Perikanan\\5.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\15. Wersar - Pelabuhan Perikanan\\10.jpg' width='300'/>",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\15. Wersar - Pelabuhan Perikanan\\15.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "1+343"
},
{
    "FID": 47,
    "ID": 14,
    "NAMA_RUAS": "WERMIT - WERSIMAR",
    "KECAMATAN_": "TEMINABUAN",
    "PANJANG_KM": 8.886,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 8.886,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 4.886,
    "BAIK__PERS": "54,99%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0,00%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0,000%",
    "RUSAKBERAT": 4,
    "RUSAKBER00": "45,01%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\14. Wermit - Wersimar\\18.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\14. Wermit - Wersimar\\46.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\14. Wermit - Wersimar\\16.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "8+886"
},
{
    "FID": 48,
    "ID": 25,
    "NAMA_RUAS": "SESNA - BOLDON - WEHALI",
    "KECAMATAN_": "WAYER-TEMINABUAN",
    "PANJANG_KM": 25.43,
    "LEBAR_M": 6,
    "LAPEN_KM": 7.807,
    "BETON_KM": 0,
    "TELFORD_KE": 17.623,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 3.478,
    "BAIK__PERS": "13,68%",
    "SEDANG_KM": 5.63,
    "SEDANG_PER": "22,14%",
    "RUSAKRINGA": 4.258,
    "RUSAKRIN00": "16,74%",
    "RUSAKBERAT": 12.064,
    "RUSAKBER00": "47,44%",
    "LHR": 0,
    "AKSES_KE_N": "P",
    "KETERANGAN": "PROVINSI",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\5.jpg' width='300'/>",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\93.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\36.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\144.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\4.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\25. Sesna - Boldon - Wehali\\124.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "",
    "STA_AKHIR": ""
},
{
    "FID": 49,
    "ID": 34,
    "NAMA_RUAS": "JALUR 1-7 -HASIK JAYA -BUMI AJO",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 20.99,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 11.784,
    "BETON_KM": 0,
    "TELFORD_KE": 9.206,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 3.99,
    "BAIK__PERS": "19,01%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 17,
    "RUSAKBER00": "80,99",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\34. Jalur 1-7 Hasik Jaya Bumi Ajo\\Jalur 4\\33.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\34. Jalur 1-7 Hasik Jaya Bumi Ajo\\Jalur 6\\9.jpg' width='300'/>",
    "FOTO_ASPAL": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\34. Jalur 1-7 Hasik Jaya Bumi Ajo\\Jalur 7\\13.jpg' width='300'/>",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\34. Jalur 1-7 Hasik Jaya Bumi Ajo\\Jalur 3\\1.jpg' width='300'/>",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000, 9+206",
    "STA_AKHIR": "9+206, 20+990"
},
{
    "FID": 50,
    "ID": 45,
    "NAMA_RUAS": "LINGKAR KAMPUNG ANI - MANELEK - DEPAN KANTOR DPR",
    "KECAMATAN_": "TEMINABUAN-WAYER",
    "PANJANG_KM": 8.297,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 7.575,
    "TANAH_KM": 0.722,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 2.897,
    "SEDANG_PER": "34.92%",
    "RUSAKRINGA": 1.238,
    "RUSAKRIN00": "14,925",
    "RUSAKBERAT": 4.162,
    "RUSAKBER00": "50,16%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\45. Lingkar Kampung Ani - Manelek - Depan Kantor DPR\\38.jpg' width='300'/>",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\45. Lingkar Kampung Ani - Manelek - Depan Kantor DPR23.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\45. Lingkar Kampung Ani - Manelek - Depan Kantor DPR\\11.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\45. Lingkar Kampung Ani - Manelek - Depan Kantor DPR\\32.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\45. Lingkar Kampung Ani - Manelek - Depan Kantor DPR\\35.jpg' width='300'/>",
    "STA_AWAL": "0+000, 3+440, 4+162",
    "STA_AKHIR": "3+440, 4+162, 8+297"
},
{
    "FID": 51,
    "ID": 48,
    "NAMA_RUAS": "KAMRO - HAIMARAN",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 6.662,
    "LEBAR_M": 0,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 6.662,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 6.662,
    "SEDANG_PER": "100%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "6+662"
},
{
    "FID": 52,
    "ID": 51,
    "NAMA_RUAS": "TOKAS - BENDUNGAN - KAMP. SABUN",
    "KECAMATAN_": "MOSWAREN",
    "PANJANG_KM": 4.543,
    "LEBAR_M": 6,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 2.143,
    "TANAH_KM": 2400,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0.%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 1943,
    "RUSAKRIN00": "42.77%",
    "RUSAKBERAT": 2.6,
    "RUSAKBER00": 57.23,
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\51. Tokas - Bendungan - Kampung Sabun\\6.jpg' width='300'/>",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\51. Tokas - Bendungan - Kampung Sabun\\24.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\51. Tokas - Bendungan - Kampung Sabun\\31.jpg' width='300'/>",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\51. Tokas - Bendungan - Kampung Sabun\\34.jpg' width='300'/>",
    "STA_AWAL": "0+000, 2+400",
    "STA_AKHIR": "2+400, 4+543"
},
{
    "FID": 53,
    "ID": 7,
    "NAMA_RUAS": "MANGGROHOLO - SIRA",
    "KECAMATAN_": "SAIFI",
    "PANJANG_KM": 0.7,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0.7,
    "TELFORD_KE": 0,
    "TANAH_KM": 0,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0.7,
    "BAIK__PERS": "100%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0.000%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": 0,
    "RUSAKBERAT": 0,
    "RUSAKBER00": "0%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\07. Manggroholo - Sira\\2.jpg' width='300'/>",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\07. Manggroholo - Sira\\4.jpg' width='300'/>",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "0+700"
},
{
    "FID": 54,
    "ID": 10,
    "NAMA_RUAS": "KAYABO - KAMPUNG RAIS",
    "KECAMATAN_": "SAIFI",
    "PANJANG_KM": 0.978,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 0.978,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 0.978,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\10. Kayabo - Kampung Rais\\2.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\10. Kayabo - Kampung Rais\\7.jpg' width='300'/>",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "0+975"
},
{
    "FID": 55,
    "ID": 56,
    "NAMA_RUAS": "TAROF - TAMBANI",
    "KECAMATAN_": "KOKODA",
    "PANJANG_KM": 14.11,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 14.11,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 14.11,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "14+110"
},
{
    "FID": 56,
    "ID": 55,
    "NAMA_RUAS": "ATHORI - TAMBANI",
    "KECAMATAN_": "KOKODA-KOKODA UTARA",
    "PANJANG_KM": 33.67,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 33.67,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 33.67,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "33+670"
},
{
    "FID": 57,
    "ID": 57,
    "NAMA_RUAS": "BEDARE - ISAGO",
    "KECAMATAN_": "INAWATAN",
    "PANJANG_KM": 26.54,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 26.54,
    "BELUMTEMBU": 26.54,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 26.54,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "26+540"
},
{
    "FID": 58,
    "ID": 52,
    "NAMA_RUAS": "ELES - WEHALI",
    "KECAMATAN_": "TEMINABUAN-SAWIAT",
    "PANJANG_KM": 14.19,
    "LEBAR_M": 8,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 14.19,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 14.19,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "14+190"
},
{
    "FID": 59,
    "ID": 53,
    "NAMA_RUAS": "BATU PAYUNG - KAKAS",
    "KECAMATAN_": "SEREMUK-SAWIAT",
    "PANJANG_KM": 30.3,
    "LEBAR_M": 5.5,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 30.3,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0.000%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0.000%",
    "RUSAKBERAT": 30.3,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\53. Kakas - Batu Payung\\13.jpg' width='300'/>",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "<img src= 'E:\\PAK ASMAR\\DATA BASE JALAN SORONG\\53. Kakas - Batu Payung' width='300'/>",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "30+300"
},
{
    "FID": 60,
    "ID": 54,
    "NAMA_RUAS": "BEDARE - KASWERI",
    "KECAMATAN_": "INAWATAN-KOKODA",
    "PANJANG_KM": 20.82,
    "LEBAR_M": 0,
    "LAPEN_KM": 0,
    "BETON_KM": 0,
    "TELFORD_KE": 0,
    "TANAH_KM": 20.82,
    "BELUMTEMBU": 0,
    "BAIK_KM": 0,
    "BAIK__PERS": "0%",
    "SEDANG_KM": 0,
    "SEDANG_PER": "0%",
    "RUSAKRINGA": 0,
    "RUSAKRIN00": "0%",
    "RUSAKBERAT": 20.82,
    "RUSAKBER00": "100%",
    "LHR": 0,
    "AKSES_KE_N": "K",
    "KETERANGAN": "KABUPATEN",
    "FOTO": "",
    "FOTO_1": "",
    "FOTO_12": "",
    "FOTO_12_13": "",
    "FOTO_ASPAL": "",
    "FOTO_BETON": "",
    "FOTO_TELFO": "",
    "FOTO_TANAH": "",
    "STA_AWAL": "0+000",
    "STA_AKHIR": "20+820"
}
]